(TeX-add-style-hook "examples"
 (lambda ()
    (LaTeX-add-bibliographies)
    (LaTeX-add-labels
     "sec:pima-indi-diab"
     "sec:setup"
     "sec:stoch-model-search"
     "sec:incl-prob"
     "sec:sampl-model-param"
     "sec:curve-estimates"
     "sec:post-processing"
     "sec:prediction-samples"
     "sec:model-averaging")
    (TeX-run-style-hooks
     "Sweave"
     "nogin"
     "tikz"
     "natbib"
     "longnamesfirst"
     "round"
     "subfig"
     "amssymb"
     "amsmath"
     "sumlimits"
     "intlimits"
     "namelimits"
     "url"
     "hyperref"
     "textcomp"
     "fontenc"
     "T1"
     "babel"
     "inputenc"
     "utf8"
     "latex2e"
     "scrreprt10"
     "scrreprt"
     "UKenglish")))

